app/users/models.py
from app import db


class User(db.Model):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)

    def __repr__(self):
        return f"User('{self.email}')"

app/users/__init__.py
from flask import Blueprint

user_bp = Blueprint("users", __name__, url_prefix="/user", template_folder="templates")
from . import views

app/users/views.py
from flask import (
    flash,
    make_response,
    render_template,
    request,
    redirect,
    session,
    url_for,
)
from . import user_bp
from app import db
from .models import User


@user_bp.route("/hi/<string:name>")
def greeting(name):
    name = name.upper()
    age = request.args.get("age", 0, int)
    return render_template("users/hi.html", name=name, age=age)


@user_bp.route("/admin")
def admin():
    to_url = url_for("users.greeting", age=45,
                     name="administrator", external=True)
    print(to_url)
    return redirect(to_url)


@user_bp.route("/profile")
def get_profile():
    if "username" in session:
        username = session["username"]
        return render_template(
            "users/profile.html", username=username, cookies=request.cookies
        )
    flash("You need to login", "danger")
    return redirect(url_for("users.login"))


@user_bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        correct_username = "admin"
        correct_password = "admin"
        username = request.form.get("username")
        password = request.form.get("password")
        if username == correct_username and password == correct_password:
            session["username"] = username
            flash("You are successfully logged in", "success")
            return redirect(url_for("users.get_profile"))
        else:
            flash("Invalid username or password", "danger")
            return redirect(url_for("users.login"))
    if "username" in session:
        flash("You are already logged in", "info")
        return redirect(url_for("users.get_profile"))
    return render_template("users/login.html")


@user_bp.route("/logout")
def logout():
    session.pop("username", None)
    flash("You are successfully logged out", "info")
    return redirect(url_for("users.login"))


@user_bp.route("/set_cookie", methods=["GET", "POST"])
def set_cookie():
    key = request.form.get("key")
    value = request.form.get("value")
    max_age = request.form.get("max_age", 60, int)
    if not key or not value or not max_age:
        flash("Заповніть всі поля", "danger")
        return redirect(url_for("users.get_profile"))
    flash(f"Кука {key} зі значенням {value} встановлена", "success")

    response = make_response(redirect(url_for("users.get_profile")))
    response.set_cookie(key, value, max_age=max_age)
    return response


@user_bp.route("/get_cookie", methods=["GET", "POST"])
def get_cookie():
    username = request.cookies.get("username")
    return f"Користувач: {username}"


@user_bp.route("/delete_cookie", methods=["GET", "POST"])
def delete_cookie():
    key = request.form.get("key")
    flash(f"Кука {key} видалена", "info")
    response = make_response(redirect(url_for("users.get_profile")))
    response.set_cookie(key, "", expires=0)
    return response


@user_bp.route("/delete_all_cookies", methods=["GET", "POST"])
def delete_all_cookies():
    flash("Всі кукі видалено", "info")
    response = make_response(redirect(url_for("users.get_profile")))
    for key in request.cookies:
        response.set_cookie(key, "", expires=0)
    return response

app/users/templates/users/hi.html
{% extends "base.html" %}
{% block title %}Greeting Page{% endblock %}

{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Flask App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.greeting', name='John', age=30) }}">Greet John</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('users.admin') }}">Admin</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
{% endblock %}


{% block content %}

<div class="container mt-4">
    <div class="card shadow">
        <div class="card-body">
            <h1 class="card-title">Hello:</h1>
            <h2 class="card-subtitle mb-2 text-muted">Name: {{ name }}</h2>

            {% if age %}
            <h2 class="card-text text-success">Age: {{ age }}</h2>
            {% else %}
            <h2 class="card-text text-danger">Age: empty</h2>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

app/users/templates/users/login.html
{% extends "base.html" %}
{% block title %}Greeting Page{% endblock %}
{% block content %}
<h1>Login</h1>
<form method="POST">
    <div class="mb-3">
        <label for="username" class="form-label">Username</label>
        <input type="text" class="form-control" id="username" name="username">
    </div>
    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" id="password" name="password">
    </div>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

app/users/templates/users/profile.html
{% extends "base.html" %}
{% block title %}Greeting Page{% endblock %}
{% block content %}
<div class="container mt-5">
    <h1>Hi, {{username}}!</h1>
    <p>Ви ввійшли як <strong>{{username}}</strong></p>
    <a href="{{ url_for('users.logout') }}" class="btn btn-danger">Logout</a>
    <div class="mt-5">

        <h3>Додати кукі</h3>
        <form method="POST" action="{{ url_for('users.set_cookie') }}">
            <div class="mb-3">
                <label for="key" class="form-label">Ключ кукі</label>
                <input type="text" class="form-control" id="key" name="key" required>
            </div>
            <div class="mb-3">
                <label for="value" class="form-label">Значення кукі</label>
                <input type="text" class="form-control" id="value" name="value" required>
            </div>
            <div class="mb-3">
                <label for="max_age" class="form-label">Термін дії (сек.)</label>
                <input type="number" class="form-control" id="max_age" name="max_age" value="60" required>
            </div>
            <button type="submit" class="btn btn-primary">Дати кукі</button>
        </form>
    </div>
    <div class="mt-5">
        <h3>Видалити кукі</h3>
        <form method="post" action="{{ url_for('users.delete_cookie') }}" class="mt-3">
            <div class="form-group">
                <label for="key">Видалити cookie за ключем</label>
                <input type="text" class="form-control" id="key" name="key">
            </div>
            <button type="submit" class="btn btn-danger mt-3">Видалити cookie</button>
        </form>

        <form method="post" action="{{ url_for('users.delete_all_cookies') }}" class="mt-3">
            <button type="submit" class="btn btn-danger">Видалити всі cookie</button>
        </form>
    </div>
    <div class="mt-5">
        <h3>Список всі кукі:</h3>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Key</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                {% for key, value in cookies.items() %}
                <tr>
                    <td>{{ key }}</td>
                    <td>{{ value }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}