app/posts/models.py
from app import db
from datetime import datetime as dt
from sqlalchemy.orm import backref


post_tags = db.Table(
    'post_tags',
    db.Column('post_id', db.Integer, db.ForeignKey(
        'posts.id'), primary_key=True),
    db.Column('tag_id', db.Integer, db.ForeignKey('tags.id'), primary_key=True)
)


class Post(db.Model):
    __tablename__ = "posts"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    content = db.Column(db.Text, nullable=False)
    posted = db.Column(db.DateTime, default=dt.now())
    is_active = db.Column(db.Boolean, default=True)
    category = db.Column(db.String(50))
    # author = db.Column(db.String(20), nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)
    author = db.relationship("User", backref=backref(
        "posts", lazy="dynamic"), lazy="joined")
    tags = db.relationship("Tag", secondary=post_tags, back_populates="posts")

    def __repr__(self):
        return f"<Post(title={self.title})>"


class Tag(db.Model):
    __tablename__ = "tags"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(50), unique=True, nullable=False)
    posts = db.relationship(
        "Post", secondary=post_tags, back_populates="tags")

app/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import (
    BooleanField,
    DateTimeLocalField,
    SelectField,
    SelectMultipleField,
    StringField,
    TextAreaField,
    SubmitField,
)
from wtforms.validators import DataRequired, Length
from app.posts.models import Tag

CATEGORIES = [
    ("tech", "Technology"),
    ("science", "Science"),
    ("lifestyle", "Lifestyle"),
]


class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired(), Length(2)])
    content = TextAreaField(
        "Content", render_kw={"rows": 5, "cols": 40}, validators=[DataRequired()]
    )
    is_active = BooleanField("Active Post")
    publish_date = DateTimeLocalField("Publish Date", format="%Y-%m-%dT%H:%M")
    category = SelectField("Category", choices=CATEGORIES,
                           validators=[DataRequired()])
    author_id = SelectField('Author', coerce=int)
    tags = SelectMultipleField('Tags', coerce=int)

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        self.tags.choices = [(tag.id, tag.name) for tag in Tag.query.all()]
    submit = SubmitField("Add Post")

app/posts/__init__.py
from flask import Blueprint

post_bp = Blueprint(
    "posts",
    __name__,
    url_prefix="/post",
    template_folder="templates/posts",
    static_folder="static",
    static_url_path="/static_for_posts",
)
from . import views

app/posts/views.py
from flask import render_template, redirect, flash, url_for
from . import post_bp
from .forms import PostForm
from app.posts.models import Post, Tag
from app.users.models import User
from app import db


@post_bp.route("/")
def get_posts():
    posts = Post.query.order_by(Post.posted.asc()).all()
    return render_template("posts.html", posts=posts)


@post_bp.route("/<int:id>")
def get_post(id):
    post = Post.query.get(id)
    return render_template("detail-post.html", post=post)


@post_bp.route("/add_post", methods=["GET", "POST"])
def add_post():
    form = PostForm()
    authors = User.query.all()
    form.author_id.choices = [(author.id, author.username)
                              for author in authors]
    if form.validate_on_submit():
        new_post = Post(
            title=form.title.data,
            content=form.content.data,
            posted=form.publish_date.data,
            is_active=form.is_active.data,
            category=form.category.data,
            user_id=form.author_id.data,
        )
        tags = Tag.query.filter(Tag.id.in_(form.tags.data)).all()
        new_post.tags.extend(tags)
        db.session.add(new_post)
        db.session.commit()
        flash("Post added successfully", "success")
        return redirect(url_for("posts.get_posts"))
    return render_template("add_post.html", form=form)


@post_bp.route("/edit_post/<int:id>", methods=["GET", "POST"])
def edit_post(id):
    post = db.get_or_404(Post, id)
    form = PostForm(obj=post)
    form.publish_date.data = post.posted
    authors = User.query.all()
    form.author_id.choices = [(author.id, author.username)
                              for author in authors]
    tags = [tag.id for tag in post.tags]
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.posted = form.publish_date.data
        post.is_active = form.is_active.data
        post.category = form.category.data
        post.user_id = form.author_id.data
        tags = Tag.query.filter(Tag.id.in_(form.tags.data)).all()
        post.tags = tags
        db.session.commit()
        flash("Post updated successfully", "success")
        return redirect(url_for(".get_posts"))
    return render_template("edit-post.html", form=form, post=post)


@post_bp.route("/delete_post/<int:id>", methods=["POST"])
def delete_post(id):
    post = db.get_or_404(Post, id)
    db.session.delete(post)
    db.session.commit()
    flash("Post deleted successfully", "success")
    return redirect(url_for(".get_posts"))

app/posts/templates/posts/add_post.html
{% extends 'base.html' %}

{% block title %}Add Post{% endblock %}

{% block content %}
<h2>Add New Post</h2>
<form method="POST" action="" novalidate>
    {{ form.hidden_tag() }}
    {% from 'form_macros.html' import render_field %}
    {{ render_field(form.title) }}
    {{ render_field(form.content) }}
    <br>
    <div class="form-group form-check">
        {{ form.is_active(class="form-check-input") }}
        {{ form.is_active.label(class="form-check-label") }}
    </div>
    <br>
    {{ render_field(form.publish_date) }}
    {{ render_field(form.category) }}
    {{ render_field(form.author_id) }}
    {{ render_field(form.tags) }}
    <br>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Add Post</button>
    </div>
</form>
{% endblock %}

app/posts/templates/posts/detail-post.html
{% extends "base.html" %}
{% block title %}Post Detail{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('.static', filename='css/posts.css') }}">
{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="card p-3">
        <h1>{{ post.title }}</h1>
        <img class="img-card" src="{{ url_for('.static', filename='img/logo.png') }}">
        <p>ID: {{ post.id }}</p>
        <p>Category: {{ post.category }}</p>
        <p>Published: {{ post.posted }}</p>
        <p>By: {{ post.author.username }}</p>
        <p class="mt-4">{{ post.content }}</p>
        <p class="card-text text-muted">Tags: {% for tag in post.tags %}{{ tag.name }}{% if not
            loop.last %}, {%
            endif %}{% endfor %}
        </p>
        <form action="{{ url_for('.delete_post', id=post.id) }}" method="POST">
            <button type="submit" class="btn btn-danger">Delete</button>
        </form>
        <br>
        <form action="{{ url_for('.edit_post', id=post.id) }}" method="POST">
            <button type="submit" class="btn btn-primary">Edit</button>
        </form>
        <div>
            <a href="{{ url_for('posts.get_posts') }}" class="btn btn-secondary mt-3">Back to Posts</a>
        </div>
    </div>
</div>
{% endblock %}

app/posts/templates/posts/edit-post.html
{% extends 'base.html' %}

{% block title %}Edit Post{% endblock %}

{% block content %}
<h2>Edit Post</h2>
<form method="POST" action="" novalidate>
    {{ form.hidden_tag() }}
    {% from 'form_macros.html' import render_field %}
    {{ render_field(form.title) }}
    {{ render_field(form.content) }}
    <br>
    <div class="form-group form-check">
        {{ form.is_active(class="form-check-input") }}
        {{ form.is_active.label(class="form-check-label") }}
    </div>
    <br>
    {{ render_field(form.publish_date) }}
    {{ render_field(form.category) }}
    {{ render_field(form.author_id) }}
    {{ render_field(form.tags) }}
    <br>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Edit Post</button>
    </div>
</form>
{% endblock %}

app/posts/templates/posts/posts.html
{% extends "base.html" %}
{% block title %}Posts{% endblock %}

{% block css %}
<link rel="stylesheet" href="{{ url_for('.static', filename='css/posts.css') }}">
{% endblock %}
{% block content %}
<h1 class="mb-4 my-class">Articles</h1>
<div class="container mt-5">
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4 mb-4">
            <div class="card h-100">
                <div class="card-body">
                    <img class="img-card" src="{{ url_for('.static', filename='img/logo.png') }}">
                    <h5 class="card-title text-primary">{{post["title"]}}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">Author: {{ post.author.username }}</h6>
                    <p class="card-text">{{ post.content[:100] }}...</p>
                    <p class="card-text">Category: {{ post.category }}</p>
                    <p class="card-text">Published: {{ post.posted }}</p>
                    <p class="card-text text-muted">Tags: {% for tag in post.tags %}{{ tag.name }}{% if not
                        loop.last %}, {%
                        endif %}{% endfor %}
                    </p>
                    <div>
                        <a href="{{ url_for('posts.get_post', id=post.id) }}"
                            class="btn btn-sm btn-outline-primary float-end">Read More</a>
                    </div>
                    <form action="{{ url_for('.delete_post', id=post.id) }}" method="POST" class="mb-3">
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                    <form action="{{ url_for('.edit_post', id=post.id) }}" method="POST">
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
        <a href="{{ url_for('posts.add_post') }}" class="btn btn-primary my-4">Add Post</a>
    </div>
</div>
{% endblock %}